apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trigra.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "trigra.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trigra.fullname" . }}-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trigra.fullname" . }}-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "trigra.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "trigra.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
