apiVersion: v1
kind: Secret
metadata:
  name: trigra-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  github-token: {{ .Values.github.token | quote }}
  webhook-secret: {{ .Values.github.webhookSecret | quote }}
