apiVersion: v1
kind: Service
metadata:
  name: trigra
  namespace: default
  labels:
    app: trigra
spec:
  type: LoadBalancer
  ports:
  - port: 82
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: trigra
